### ISSUE TITLE
any form to load from a state?

### ISSUE THREAD

**Issue by rafaelmndz** [denimar/deni-react-treeview#1]
i tried to load data from a state but when the page load the tree view shows empty
![screenshot_6](https://cloud.githubusercontent.com/assets/28906269/26463422/d0840d34-4149-11e7-834e-af0d2f44ebe8.png)

code:
![screenshot_7](https://cloud.githubusercontent.com/assets/28906269/26463491/162f102c-414a-11e7-857e-d717c110dc42.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/28906269/26463307/73f1bbc0-4149-11e7-953f-a7f9d1d8f7df.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/28906269/26463308/73f22916-4149-11e7-8dc4-ae86b3cbc646.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/28906269/26463367/a3c57422-4149-11e7-81b2-cefbf4b67642.png)

also i tried:
![screenshot_3](https://cloud.githubusercontent.com/assets/28906269/26463309/73f59d8a-4149-11e7-91a7-cd09db4b911b.png)

**Comment by denimar** [comment]
Hi Rafael,

In fact there was a problem, but it is fixed now. 
Try again, please.

See the example by clicking in the link below:
https://jsfiddle.net/denimar/ybbrpx0u/

Whatever problem, be free to contact me.

Best regards

Denimar de Moraes

**Comment by rafaelmndz** [comment]
Hi thanks for your prompt response, but in the example the state is changed directly with the values , how would be the case using fetch? And it is possible without using a button to load the tree.

**Comment by denimar** [comment]
You're welcome!

As far as what I saw, your code should be working now.
Be sure you are using the version 0.1.11 (see it in package.json). It should be working.

Maybe, you can use this example as well: https://denimar.github.io/deni-react-treeview/examples/#/json

**Comment by rafaelmndz** [comment]
actually the issue is solved on  0.1.11 . not parse necessary .
Thanks. ;)
