### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by thmoeller** [denimar/deni-react-treeview#11]
Hi

should be fixed wit 02.11, but still present for me with 02.14.

Kind regards

Moe

Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `DeniReactTreeView`. See https://fb.me/react-warning-keys for more information.
    in div (created by DeniReactTreeView)

**Comment by inhuman** [comment]
waiting..

**Comment by inhuman** [comment]
up

**Comment by denimar** [comment]
with 0.2.15 is working perfectly.

**Comment by denimar** [comment]
with 0.2.15 is working perfectly.

**Comment by wirydes** [comment]
i'm getting the same issue version 0.2.15 just happen in the first time you render the component with the three view
