### ISSUE TITLE
multiple treeviews - data does not load right. 

### ISSUE THREAD

**Issue by davvit** [denimar/deni-react-treeview#13]
I have two treeViews as follows: 
i am using the same jsonUrl as the examples and same fruitAndVegetables data.

```
        let jsonUrl = 'https://denifakedata.herokuapp.com/tree/countries';

          <TreeView showCheckbox={true} theme="metro" json={jsonUrl} />

           <TreeView showIcon={false}
                    className="onrenderitem-example"
                    ref="treeview"
                    showCheckbox={this.props.checkbox? true : false}
                    items={fruitsAndVegetables}
                    onExpanded={this.onExpanded.bind(this)}
                    selectRow={true}
                    onRenderItem={this.onRenderItem.bind(this)}
                        onCheckItem={this.onCheckItem.bind(this)} />
         
```

this is the result. The second treeview shows data from TreeView 1...

![image](https://user-images.githubusercontent.com/4433698/52490869-60715780-2b8b-11e9-8acc-c5b24fdacbb9.png)

Here is a codesandbox -   https://codesandbox.io/s/84y066wl62
on load everything looks fine but when you go to expand the second treeview the first treeview data shows.

@denimar

**Comment by denimar** [comment]
Hi davvit!
This issue was fixed in version '0.0.2.20'
Thank you!
