### ISSUE TITLE
Issue self.setState is not a function at line 836 of deni-react-treeview.js

### ISSUE THREAD

**Issue by tbuquet** [denimar/deni-react-treeview#2]
Hello, and thanks for this component!

There seems to be a bug at line 836 of the component with self.setState not being a function.
It is thrown on any example https://denimar.github.io/deni-react-treeview/examples/#/json by double clicking on a node.

Using latest version of Chrome.

**Comment by denimar** [comment]
Hi tbuquet,

The bug was fixed.

Many Thanks!
