### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by ino20ain01** [denimar/deni-react-treeview#6]
I add button action but console alert warning (Each child in an array or iterator should have a unique "key" prop).
Sorry because your English not good.

![image](https://user-images.githubusercontent.com/32928947/47197518-f2f9ab00-d390-11e8-98b8-ede192063238.png)

**Comment by denimar** [comment]
This issue was fixed in version 0.2.11.
Thank you!
